#ifndef REPORTCREATEFORHTMLEXPORT_H
#define REPORTCREATEFORHTMLEXPORT_H

#include <QtCore/qglobal.h>

#if not defined(LIBRARY_UNEXPORT)
    #if defined(REPORTCREATEFORHTML_LIBRARY)
    #  define REPORTCREATEFORHTML_EXPORT Q_DECL_EXPORT
    #else
    #  define REPORTCREATEFORHTML_EXPORT Q_DECL_IMPORT
    #endif
#else
    #  define REPORTCREATEFORHTML_EXPORT
#endif

#endif // REPORTCREATEFORHTMLEXPORT_H
